{% set name = "pysonar" %}
{% set version = "1.3.0.4086" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pysonar-{{ version }}.tar.gz
  sha256: b05f887503de37d13bfec799a3b1d52fea084a4fd2ff06fdd2d2c8f9b73a4634

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - pysonar = pysonar_scanner.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - jproperties 2.1.2
    - pyfakefs 5.8.0
    - requests 2.32.4
    - responses 0.25.6
    - tomli 2.2.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - pysonar_scanner
  commands:
    - pysonar --help

about:
  home: https://github.com/SonarSource/sonar-scanner-python
  summary: Sonar Scanner for the Python Ecosystem
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RajeshwariSubramaniam
